cobbzilla/cobbzilla-utils

src/main/java/org/cobbzilla/util/handlebars/ESignInsertion.java

Introduce ESignInsertion

---

src/main/resources/org/cobbzilla/util/javascript/standard_js_lib.js

Check for false (as find result) also within contains method

---

src/main/resources/org/cobbzilla/util/javascript/standard_js_lib.js

Fix fetching element from custom JS objects

---

src/main/java/org/cobbzilla/util/daemon/ZillaRuntime.java

Log internal exception (do not hide it)

---

src/main/java/org/cobbzilla/util/handlebars/HandlebarsUtil.java
src/main/java/org/cobbzilla/util/io/FileUtil.java
src/main/java/org/cobbzilla/util/string/Base64.java

Add textFile handlebars helper

---

src/main/java/org/cobbzilla/util/xml/XmlUtil.java

Add method to search for tag and content within XML

---

src/main/java/org/cobbzilla/util/http/HttpUtil.java

Fix response content handling in case of 204 resonse status

---

src/main/java/org/cobbzilla/util/http/HttpContentTypes.java
src/main/java/org/cobbzilla/util/http/HttpRequestBean.java
src/main/java/org/cobbzilla/util/http/HttpResponseBean.java

Fix setting and creating headers in HttpRequestBean and HttpResponseBean

---

src/main/java/org/cobbzilla/util/http/HttpUtil.java

requests not limited to POST

---

src/main/java/org/cobbzilla/util/http/HttpEventErrorHandler.java

Added interface HttpEventErrorHandler

---

src/main/java/org/cobbzilla/util/string/StringUtil.java
src/main/java/org/cobbzilla/util/xml/ElementIdGenerator.java
src/main/java/org/cobbzilla/util/xml/XmlUtil.java

Small extensions

---

src/main/java/org/cobbzilla/util/string/StringUtil.java

Better expression for comparing strings extended equality

---

src/main/resources/org/cobbzilla/util/javascript/standard_js_lib.js

Fix string vs. number index problems and length vs. size

---

src/main/java/org/cobbzilla/util/javascript/JsEngine.java

add evaluate long with default values

---

src/main/java/org/cobbzilla/util/reflect/ReflectionUtil.java

Fix set null Object[] value for privitive types

---

src/main/java/org/cobbzilla/util/handlebars/HandlebarsUtil.java

Fix condition in handlebars find to work well with enums

---

src/main/java/org/cobbzilla/util/collection/CombinationsGenerator.java

Add util class for generating combinations of elements

---

src/main/java/org/cobbzilla/util/reflect/ReflectionUtil.java

@cobbzilla please review (after related automatic tests are done if all is well)

Copy from map to map objects properly

---

src/main/java/org/cobbzilla/util/handlebars/HandlebarsUtil.java

Add handlebars helper for getting first nonempty element

---

src/main/java/org/cobbzilla/util/handlebars/HandlebarsUtil.java

Fix adding negative periods to datetime

---

src/main/java/org/cobbzilla/util/daemon/ZillaRuntime.java

Use proper (element's) type in array copy method
